# Generated by Django 5.0.1 on 2024-01-22 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tc', models.CharField(editable=False, max_length=45, unique=True)),
                ('vc', models.CharField(max_length=45)),
                ('verification_status', models.CharField(max_length=45)),
                ('can_count', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lc', models.CharField(max_length=45, null=True)),
                ('stc', models.CharField(max_length=45, null=True)),
                ('ptc', models.CharField(max_length=45, null=True)),
                ('mfg', models.DateTimeField()),
                ('bb', models.DateTimeField(null=True)),
                ('manufacturing_time', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('image_path', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
